### ISSUE TITLE
Blocker: This looks like Comic Sans

### ISSUE THREAD

**Issue by mariusstrom** [shannpersand/comic-shanns#1]
I feel like someone needed to file this obvious issue.

**Comment by kilobyte** [comment]
Well, that's the point.  If you want a programming font that's awesome but follows only the most vague idea, there's [Fantasque Sans](https://github.com/belluzj/fantasque-sans), if you want a proportional font that fixes the worst downsides of the original, there's [Comic Neue](http://comicneue.com/).

But if what you want is a programming font that a passer-by won't be able to tell from the original, Comic Shanns shines.  It's great for trolling cow orkers (tested!).

**Comment by shannpersand** [comment]
[Won't fix] Pls wait for PapyrusMono

**Comment by davelab6** [comment]
@mariusstrom in the USA, typeface designs are not subject to copyright, so making fonts that look similar is not a problem as it might be if they were. The inherent similarity of letterforms makes it a minefield if that was the case. In Europe there are shorter copyrights on typefaces, and since Comic Sans is from 1994, those have all expired long ago.

**Comment by mariusstrom** [comment]
> [@mariusstrom](https://github.com/mariusstrom) in the USA, typeface designs are not subject to copyright, so making fonts that look similar is not a problem as it might be if they were. The inherent similarity of letterforms makes it a minefield if that was the case. In Europe there are shorter copyrights on typefaces, and since Comic Sans is from 1994, those have all expired long ago.

Thank you for replying to a 7-year old issue I created in jest.
